const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 4,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },

  {
    id: 5,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },

  {
    id: 6,
    title: "aloo tikki",
    category: "breakfast",
    price: 16.99,
    img: "./images/alootikki.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 7,
    title: "Chocolate pastry",
    category: "dessert",
    price: 26.99,
    img: "./images/chocolatecake.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 8,
    title: "Paneer Pulao",
    category: "lunch",
    price: 19.99,
    img: "./images/pannerpulao.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 9,
    title: "Dosa",
    category: "breakfast",
    price: 6.99,
    img: "./images/dosa.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 10,
    title: "Double Cheese Burger",
    category: "dinner",
    price: 26.99,
    img: "./images/doublecheese.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 11,
    title: "Hakka Noddles",
    category: "dinner",
    price: 11.99,
    img: "./images/hakka.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 12,
    title: "falafel with hummus",
    category: "lunch",
    price: 26.99,
    img: "./images/falafel.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 13,
    title: "french fries",
    category: "supper",
    price: 4.99,
    img: "./images/frenchfires.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 14,
    title: "Idli",
    category: "breakfast",
    price: 8.99,
    img: "./images/idli.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 15,
    title: "Nachos",
    category: "supper",
    price: 9.99,
    img: "./images/nachos.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 16,
    title: "Paneer frankie",
    category: "shakes",
    price: 16.99,
    img: "./images/pannerfrankie.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 17,
    title: "Pizza",
    category: "dinner",
    price: 16.99,
    img: "./images/pizza.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 18,
    title: "Red pasta",
    category: "breakfast",
    price: 13.99,
    img: "./images/redpasta.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
  {
    id: 19,
    title: "white pasta",
    category: "breakfast",
    price: 14.99,
    img: "./images/whitepasta.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },

  {
    id: 20,
    title: "strawberry shake",
    category: "shakes",
    price: 16.99,
    img: "./images/starwberry.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis iste, beatae ipsa aperiam itaque possimus.`,
  },
];
export default menu;
